config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :cart_items, only: [:create, :destroy]
  root to: 'albums#index'
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_many :users, through: :cart_items
  validates :title, presence: true, length: {maximum: 100}

  scope :popular, -> { where(popular: true)}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :album

  validates :user, presence: true
  validates :album, presence: true
  validates :album, uniqueness: {scope: :user}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_many :albums, through: :cart_items

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true, email: true

  before_validation -> {email.downcase!}

  def add_to_cart!(album)
    cart_item = self.cart_items.find_by(album_id: album)
    if cart_item
      cart_item.increment!(:quantity)
    else
      self.albums << album
    end
  end

  def remove_from_cart!(album)
    cart_item = self.cart_items.find_by(album_id: album)
    return unless cart_item
    if cart_item.quantity > 1
      cart_item.decrement!(:quantity)
    else
      cart_item.destroy!
    end

  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.order('created_at DESC')
    @current_user = User.current_user
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = 'Album was created!'
      redirect_to albums_path
    else
      render :new
    end

  end

  private

  def album_params
    params.require(:album).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #include AuthenticationHelper

protected

  def current_user
      @current_user ||= User.first
  end

  def require_login
    redirect_to root_path, notice: 'You are not logged in!' unless @current_user
  end

  helper_method :current_user
end

app/controllers/cart_items_controller.rb
class ApplicationController < ActionController
  before_action :require_login!

  def create
    album = Album.find_by(id: params[:album_id])
    if album
      current_user.add_to_cart!(album)
      flash[:successes] = 'Album added to your cart!'
    else
      flash[:warning] = 'Cannot find such album... '
    end
    redirect_to root_path
  end

  def destroy
    cart_item = CartItem.find_by(id: params[:id])
    if cart_item
      current_user.remove_from_cart!(cart_item.album)
      flash[:successes] = 'The item has been remove!'
    end
  else
    flash[:warning] = 'Cannot remove this item... '
  end
  redirect_to root_path
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def with_status(album)
    title = album.title
    title += content_tag(:small, 'hot!') if album.popular?
    title.html_safe

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
  # def current_user
  #   @current_user ||= User.first
  # end
end

app/views/albums/_album.html.erb
<li>
  <%= with_status album %>
  <% if @current_user %>
    <%= link_to 'Add to cart', cart_items_path(album_id: album.id), method: :post %>
  <% end %>
</li>

app/views/albums/index.html.erb
<h1>Albums</h1>

<ul id="albums"><%= render @albums %></ul>

app/views/albums/new.html.erb
<h1>New album</h1>

app/views/cart_items/_cart_items.html.erb
<li id="cart_item-<%= cart_item.id %>">
  <%= cart_item.album.title %>
  <span class="quantity"><%= cart_item.quantity %></span>
  <%= link_to '[ x ]', cart_item_path(cart_item), method: :delete %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MusicShop</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
    <% end %>
    <% if current_user %>
      Uou are logged in as <%= current_user.name %>
        <%= render 'shared/cart' %>
    <% end %>
  </header>

  <div id="content">
    <%= yield %>
  </div>

  </body>
</html>

app/views/layouts/shared/_cart.html.erb
<h2>Your cart</h2>
<ul id="cart"><%= render current_user.cart_items %></ul>